# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    # Required in Symfony 5.4+ but actually unused as there is no remember me or signed URLs on this site
    secret: '%env(APP_SECRET)%'
    http_method_override: false

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
